#!/usr/bin/perl

# Nagios plugin for IPMI sensors status checking.
#
# Especially useful on Dell Poweredge servers, and others that
# implement the Intelligent Platform Management Interface (IPMI)
# interface.
#
# (C) Chris Wilson <check_ipmi@qwirx.com>, 2005-06-04
# Released under the GNU General Public License (GPL)

# added nr state by Thomas Lange, 2008
# added %nvalue, $settings{max_temp}, $shutdown, $mstring
# modified for daemon running process, Mark Sprenger, Uni Koeln 2008
# modified to include list of exceptions, Kerim Gueney, Uni Koeln 2014

$|=1;

use warnings;
use strict;
use Sys::Hostname;

#####CONFIG VARS#######
my %settings;
my $hostname = hostname;
my @exceptions = qw/kueppers/; # list of computers to be ignored
######################

my $shutdown = 0;
my $mstring;
my $high_temp_msg=0;
my $sleeptime;
my @out;


# read configuration file
open SETTINGS, "check-temp.conf" or die;
while (my $line=<SETTINGS>) {
   chomp($line);
   (my $key, my $value) = split /=/, $line;
   $settings{$key} = $value;
}
close (SETTINGS);


print "...starting daemon: temperatur-check ... \n with limits: hightemperatur -> $settings{high_temp} , maxtemperatur -> $settings{max_temp} (leads to shutdown!!!)\n";
open(FH,">/var/run/check-temp.pid") or die "cannot open filehandle $!";
print FH $$;
close (FH);


sub trim ($) {
	my ($v) = @_;
	$v =~ s/^ +//;
	$v =~ s/ +$//;
	return $v;
}

while(1){
my %found;
my %bad;
my %nvalue; # store numeric value (without degrees C or RPM)
-c "/dev/ipmi0" or die "No /dev/ipmi0 available\n";
open IPMI, "ipmitool sdr |" or die "ipmitool: $!";

while (my $line = <IPMI>)
{
	chomp $line;
	unless ($line =~ m'^(.*) \| (.*) \| (\w+)$') { die "Bad format in ipmitool output: $line";}

	my $name  = trim $1;
	my $value = trim $2;
	my $state = trim $3;
	$name =~ tr| |_|;

	my $counter = 1;
	my $uname = "$name";
	while ($found{$uname}) {
	  $uname = $name . $counter++;
	}

	next if $state eq "ns";
	next if $state eq "nr";

	if ($state ne "ok") {$bad{$uname} = $state;}

	$found{$uname} = $value;
	($value =~ m/(\d+)/) and $nvalue{$uname} = $1;
}
close IPMI;

print time," ";

if (keys %bad) {
	print "IPMI critical: ";
	my @bad;
	foreach my $name (sort keys %bad) {
		push @bad, "$name is $bad{$name}";
	}
	print join(", ", @bad) . " ";
} else {
	print "IPMI ok ";
}

@out=();

foreach my $name (sort keys %found) {
#	next unless $name =~ m|Fan| or $name =~ m|Temp|;
	next unless $name =~ m|Temp|;
#	push @out, "$name = $found{$name}";
	push @out, "$name = $nvalue{$name}";
      }

print "(" . join(", ", @out) . ")\n";



if (!($hostname ~~ @exceptions)){
  foreach my $name (sort keys %found) {
      if ($name =~ m|Temp| && $nvalue{$name} > $settings{max_temp} && $shutdown == 0) {
	warn "$hostname reached max temperature because of $name: $nvalue{$name}\n";
	# $mstring .= "System shutdown because of $name: $nvalue{$name}\n";
	if ($settings{max_temp_action}) {
	  $mstring .= "IPMI ALARM. MAX TEMPERATURE REACHED!\nEXECUTING: $settings{max_temp_action}";
	  # system("(echo \"$mstring\";uname -n;date;echo;ipmitool sdr) | mailx sysadmin");
	  system("$settings{max_temp_action}");
	  exit $settings{max_temp_exit} if $settings{max_temp_exit};
	}
	else {
	  $shutdown = 1;
	}
      }
    }
}

if ($shutdown) {
  warn "Now shutting down\n";
  $mstring .= "IPMI ALARM. Shutdown now!\n";
 # system("(echo \"$mstring\";uname -n;date;echo;ipmitool sdr) | mailx sysadmin");
 # system("date; echo 'Now suspending to disk'; sleep 10;echo disk > /sys/power/state");
  exit 1;
}

$sleeptime=$settings{sleeptime};
foreach my $name (sort keys %found) {
  if ($name =~ m|Temp| && $nvalue{$name} > $settings{high_temp}) {

	if(!$high_temp_msg){
	      $mstring = "IPMI ALARM. HIGH TEMPERATURE!! BUT NO SHUTDOWN!!!\n";
#      	      system("(echo \"$mstring\";uname -n;date;echo;ipmitool sdr) | mailx sysadmin");
	      system("$settings{high_temp_action}") if ($settings{high_temp_action});
	      $high_temp_msg=1;
	      }
      $sleeptime = 120;
  }
}
$high_temp_msg=0 if ($sleeptime==$settings{sleeptime});
sleep ($sleeptime);

} #end of while(1)
